print("Name_of_Resturant- _SWEET_N_SALT_CUISINE")
print()
print("BILL OF RESTURANT")
print()
Bill_number=int(input("Bill number:"))
print(Bill_number)
print()
from datetime import date
today=date.today()
print("current date=",today)
print()
Name=str(input("name of constomer:"))
print(Name)
print()
Table_number=int(input("Table_number:"))
print(Table_number)
print()
tax=0.08
#these are rates of menu items.
Rate={"Roti":5,"Rice":70,"Mix_veg":100,"Ch_Masala": 200,"Desert":50,"Burger":30,"pav_bhaji": 50}
print("Enter the quntity of the odered item:")
print()
Roti=int(input("Roti[Rs.5]:"))
print(Roti)
print()
Rice=int(input("Rice[RS.70]:"))
print(Rice)
print()
Mix_veg=int(input("Mix_veg[Rs.100]:"))
print(Mix_veg)
print()
Ch_Masala=int(input("Ch_Masal[Rs.200]:"))
print(Ch_Masala)
print()
Desert=int(input("Desert[Rs.50]:"))
print(Desert)
print()
Burger=int(input("Burger[RS.30]:"))
print(Burger)
print()
pav_bhaji=int(input("pav_bhaji[Rs.50]:"))
print(pav_bhaji)
print()
#this next step is to caculate total amount.
Cost=Roti*Rate["Roti"]+Rice*Rate["Rice"]+Mix_veg*Rate["Mix_veg"]+Ch_Masala*Rate["Ch_Masala"]+Desert*Rate["Desert"]+pav_bhaji*Rate["pav_bhaji"]
Bill=Cost+Cost*tax
print("total cost = Rs.",Bill)
print()
print("THANKS FOR VISITNG !!")
print()